In [22]:
#importing the necessary libraries
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [2]:
#reading the CSV file
x = pd.read_csv("KNN-dataset.csv")

#displaying the dataframe
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
#check if there is any NULL value
x.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
#the dataset has NO null values, so don't need to handle them

In [12]:
#replacing 0 with the mean values

#all the columns in which value 0 can't be present
l_col = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for i in l_col:
    x[i] = x[i].replace(0, np.NaN) #replace 0 will NULL
    mean = int(x[i].mean(skipna=True)) #calculate mean, excluding NULL values
    x[i] = x[i].replace(np.NaN, mean) #replace NULL with mean
    
#displaying the updated dataframe    
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,155.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,155.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,155.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,155.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,29.0,155.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,155.0,30.4,0.315,23,0

In [31]:
#splitting training and testing dataset

#X will have all rows, but from 0 to 7th index columns
X = x.iloc[:, 0:8]

#y will have all rows, but the 8th index column
y = x.iloc[:, 8]

#splitting the dataset, with test-size = 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size = 0.3)

In [20]:
#standardizing data
sd = StandardScaler()

X_train = sd.fit_transform(X_train)
X_test = sd.transform(X_test)

In [34]:
#training the model 
k = math.sqrt(len(y_test))
if (math.floor(k)%2==0):
    k = math.floor(k)
else: 
    k = math.ceil(k)

classifier = KNeighborsClassifier(n_neighbors = k, p=2, metric = "euclidean")

In [35]:
#fitting the model
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=16)

In [41]:
#predicting the test set results
y_pred = classifier.predict(X_test)
y_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [44]:
#creating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[130  30]
 [ 33  38]]

In [47]:
#measuring the accuracy of the model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("F Score:", f1_score(y_test, y_pred))

Accuracy Score: 0.7272727272727273
F Score: 0.5467625899280575